// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// base_measure_order_cpp
List base_measure_order_cpp(IntegerMatrix samples, std::string method, int parallel_workers, int K, int max_exact_factorial, int seed);
RcppExport SEXP _kefV2_base_measure_order_cpp(SEXP samplesSEXP, SEXP methodSEXP, SEXP parallel_workersSEXP, SEXP KSEXP, SEXP max_exact_factorialSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type parallel_workers(parallel_workersSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type max_exact_factorial(max_exact_factorialSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(base_measure_order_cpp(samples, method, parallel_workers, K, max_exact_factorial, seed));
    return rcpp_result_gen;
END_RCPP
}
// centered_kernel_matrix_euclidean
arma::mat centered_kernel_matrix_euclidean(const arma::vec& eval_points_1, const arma::vec& eval_points_2, const arma::vec& centering_grid, double hurst_coef);
RcppExport SEXP _kefV2_centered_kernel_matrix_euclidean(SEXP eval_points_1SEXP, SEXP eval_points_2SEXP, SEXP centering_gridSEXP, SEXP hurst_coefSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type eval_points_1(eval_points_1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eval_points_2(eval_points_2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type centering_grid(centering_gridSEXP);
    Rcpp::traits::input_parameter< double >::type hurst_coef(hurst_coefSEXP);
    rcpp_result_gen = Rcpp::wrap(centered_kernel_matrix_euclidean(eval_points_1, eval_points_2, centering_grid, hurst_coef));
    return rcpp_result_gen;
END_RCPP
}
// centered_kernel_matrix_hd_euclidean
arma::mat centered_kernel_matrix_hd_euclidean(const arma::mat& eval_points_1, const arma::mat& eval_points_2, const arma::mat& centering_grid, double hurst_coef);
RcppExport SEXP _kefV2_centered_kernel_matrix_hd_euclidean(SEXP eval_points_1SEXP, SEXP eval_points_2SEXP, SEXP centering_gridSEXP, SEXP hurst_coefSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type eval_points_1(eval_points_1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type eval_points_2(eval_points_2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type centering_grid(centering_gridSEXP);
    Rcpp::traits::input_parameter< double >::type hurst_coef(hurst_coefSEXP);
    rcpp_result_gen = Rcpp::wrap(centered_kernel_matrix_hd_euclidean(eval_points_1, eval_points_2, centering_grid, hurst_coef));
    return rcpp_result_gen;
END_RCPP
}
// centered_kernel_matrix_order
arma::mat centered_kernel_matrix_order(const arma::imat& eval_points_1, const arma::imat& eval_points_2, const arma::imat& centering_grid, double hurst_coef);
RcppExport SEXP _kefV2_centered_kernel_matrix_order(SEXP eval_points_1SEXP, SEXP eval_points_2SEXP, SEXP centering_gridSEXP, SEXP hurst_coefSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::imat& >::type eval_points_1(eval_points_1SEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type eval_points_2(eval_points_2SEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type centering_grid(centering_gridSEXP);
    Rcpp::traits::input_parameter< double >::type hurst_coef(hurst_coefSEXP);
    rcpp_result_gen = Rcpp::wrap(centered_kernel_matrix_order(eval_points_1, eval_points_2, centering_grid, hurst_coef));
    return rcpp_result_gen;
END_RCPP
}
// unnormalised_density_samples
arma::vec unnormalised_density_samples(const arma::mat& centered_kernel_mat_samples, double lambda, const arma::vec& weight_vec);
RcppExport SEXP _kefV2_unnormalised_density_samples(SEXP centered_kernel_mat_samplesSEXP, SEXP lambdaSEXP, SEXP weight_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type centered_kernel_mat_samples(centered_kernel_mat_samplesSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weight_vec(weight_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(unnormalised_density_samples(centered_kernel_mat_samples, lambda, weight_vec));
    return rcpp_result_gen;
END_RCPP
}
// unnormalised_density_grids
arma::vec unnormalised_density_grids(const arma::mat& centered_kernel_mat_grids, const arma::vec& centered_kernel_self_grids, double lambda, const arma::vec& weight_vec);
RcppExport SEXP _kefV2_unnormalised_density_grids(SEXP centered_kernel_mat_gridsSEXP, SEXP centered_kernel_self_gridsSEXP, SEXP lambdaSEXP, SEXP weight_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type centered_kernel_mat_grids(centered_kernel_mat_gridsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type centered_kernel_self_grids(centered_kernel_self_gridsSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weight_vec(weight_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(unnormalised_density_grids(centered_kernel_mat_grids, centered_kernel_self_grids, lambda, weight_vec));
    return rcpp_result_gen;
END_RCPP
}
// get_dens_wo_grid_euclidean
arma::vec get_dens_wo_grid_euclidean(const arma::mat& centered_kernel_mat_samples, const arma::mat& samples, const arma::vec& base_measure_weights, double dimension, double lambda, const arma::vec& weight_vec);
RcppExport SEXP _kefV2_get_dens_wo_grid_euclidean(SEXP centered_kernel_mat_samplesSEXP, SEXP samplesSEXP, SEXP base_measure_weightsSEXP, SEXP dimensionSEXP, SEXP lambdaSEXP, SEXP weight_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type centered_kernel_mat_samples(centered_kernel_mat_samplesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type base_measure_weights(base_measure_weightsSEXP);
    Rcpp::traits::input_parameter< double >::type dimension(dimensionSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weight_vec(weight_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(get_dens_wo_grid_euclidean(centered_kernel_mat_samples, samples, base_measure_weights, dimension, lambda, weight_vec));
    return rcpp_result_gen;
END_RCPP
}
// get_dens_euclidean
Rcpp::List get_dens_euclidean(const arma::mat& centered_kernel_mat_samples, const arma::mat& centered_kernel_mat_grids, const arma::vec& centered_kernel_self_grids, const arma::mat& samples, const arma::mat& grids, const arma::vec& base_measure_weights_grid, int dimension, double lambda, const arma::vec& weight_vec);
RcppExport SEXP _kefV2_get_dens_euclidean(SEXP centered_kernel_mat_samplesSEXP, SEXP centered_kernel_mat_gridsSEXP, SEXP centered_kernel_self_gridsSEXP, SEXP samplesSEXP, SEXP gridsSEXP, SEXP base_measure_weights_gridSEXP, SEXP dimensionSEXP, SEXP lambdaSEXP, SEXP weight_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type centered_kernel_mat_samples(centered_kernel_mat_samplesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type centered_kernel_mat_grids(centered_kernel_mat_gridsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type centered_kernel_self_grids(centered_kernel_self_gridsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type grids(gridsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type base_measure_weights_grid(base_measure_weights_gridSEXP);
    Rcpp::traits::input_parameter< int >::type dimension(dimensionSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weight_vec(weight_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(get_dens_euclidean(centered_kernel_mat_samples, centered_kernel_mat_grids, centered_kernel_self_grids, samples, grids, base_measure_weights_grid, dimension, lambda, weight_vec));
    return rcpp_result_gen;
END_RCPP
}
// get_middle_points_grid
arma::vec get_middle_points_grid(double min, const arma::vec& samples, double max);
RcppExport SEXP _kefV2_get_middle_points_grid(SEXP minSEXP, SEXP samplesSEXP, SEXP maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type min(minSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< double >::type max(maxSEXP);
    rcpp_result_gen = Rcpp::wrap(get_middle_points_grid(min, samples, max));
    return rcpp_result_gen;
END_RCPP
}
// get_s_function_euclidean
arma::vec get_s_function_euclidean(const arma::vec& weight_vec, double lambda, double tau, const arma::mat& centered_kernel_mat_samples, const arma::mat& samples, const arma::vec& base_measure_weights, double dimension, bool prior_var_prob);
RcppExport SEXP _kefV2_get_s_function_euclidean(SEXP weight_vecSEXP, SEXP lambdaSEXP, SEXP tauSEXP, SEXP centered_kernel_mat_samplesSEXP, SEXP samplesSEXP, SEXP base_measure_weightsSEXP, SEXP dimensionSEXP, SEXP prior_var_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type weight_vec(weight_vecSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type centered_kernel_mat_samples(centered_kernel_mat_samplesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type base_measure_weights(base_measure_weightsSEXP);
    Rcpp::traits::input_parameter< double >::type dimension(dimensionSEXP);
    Rcpp::traits::input_parameter< bool >::type prior_var_prob(prior_var_probSEXP);
    rcpp_result_gen = Rcpp::wrap(get_s_function_euclidean(weight_vec, lambda, tau, centered_kernel_mat_samples, samples, base_measure_weights, dimension, prior_var_prob));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_kefV2_base_measure_order_cpp", (DL_FUNC) &_kefV2_base_measure_order_cpp, 6},
    {"_kefV2_centered_kernel_matrix_euclidean", (DL_FUNC) &_kefV2_centered_kernel_matrix_euclidean, 4},
    {"_kefV2_centered_kernel_matrix_hd_euclidean", (DL_FUNC) &_kefV2_centered_kernel_matrix_hd_euclidean, 4},
    {"_kefV2_centered_kernel_matrix_order", (DL_FUNC) &_kefV2_centered_kernel_matrix_order, 4},
    {"_kefV2_unnormalised_density_samples", (DL_FUNC) &_kefV2_unnormalised_density_samples, 3},
    {"_kefV2_unnormalised_density_grids", (DL_FUNC) &_kefV2_unnormalised_density_grids, 4},
    {"_kefV2_get_dens_wo_grid_euclidean", (DL_FUNC) &_kefV2_get_dens_wo_grid_euclidean, 6},
    {"_kefV2_get_dens_euclidean", (DL_FUNC) &_kefV2_get_dens_euclidean, 9},
    {"_kefV2_get_middle_points_grid", (DL_FUNC) &_kefV2_get_middle_points_grid, 3},
    {"_kefV2_get_s_function_euclidean", (DL_FUNC) &_kefV2_get_s_function_euclidean, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_kefV2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
